steps:
  - name: jessewei/alpine-bash
    args:
      - "-c"
      - |
        sed -i 's/NIGHTLYBUILD/$SHORT_SHA/g' public/index.html
    entrypoint: bash
  - name: gcr.io/cloud-builders/npm
    env:
      - "MONGO_CONNECTION_URL=${_MONGO_CONNECTION_URL}"
      - "MODEL_JSON_URL=${_MODEL_JSON_URL}"
    args:
      - run
      - create-env
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$REPO_NAME-$BRANCH_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA",
        "--region",
        "asia-southeast2",
        "--port",
        "5000",
        "--allow-unauthenticated",
      ]

timeout: 1600s
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
